import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "rgb(var(--background-rgb) / <alpha-value>)",
        surface: "rgb(var(--background-rgb) / <alpha-value>)",
        "surface-dim": "rgb(var(--background-rgb) / <alpha-value>)",
        "surface-bright": "rgb(var(--surface-container-highest-rgb) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--surface-container-lowest-rgb) / <alpha-value>)",
        "surface-container-low": "rgb(var(--surface-container-low-rgb) / <alpha-value>)",
        "surface-container": "rgb(var(--surface-container-rgb) / <alpha-value>)",
        "surface-container-high": "rgb(var(--surface-container-high-rgb) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--surface-container-highest-rgb) / <alpha-value>)",
        "surface-variant": "rgb(var(--surface-variant-rgb) / <alpha-value>)",
        "on-surface": "rgb(var(--on-surface-rgb) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--on-surface-variant-rgb) / <alpha-value>)",
        "inverse-surface": "rgb(var(--on-surface-rgb) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--surface-container-rgb) / <alpha-value>)",
        "on-background": "rgb(var(--on-background-rgb) / <alpha-value>)",
        outline: "rgb(var(--outline-rgb) / <alpha-value>)",
        "outline-variant": "rgb(var(--outline-variant-rgb) / <alpha-value>)",
        "surface-tint": "rgb(var(--accent-rgb) / <alpha-value>)",
        primary: "rgb(var(--on-surface-rgb) / <alpha-value>)",
        "on-primary": "var(--on-accent-bg)",
        "primary-container": "rgb(var(--accent-rgb) / <alpha-value>)",
        "on-primary-container": "#fffaf9",
        "inverse-primary": "#bf0023",
        "primary-fixed": "#ffdad7",
        "primary-fixed-dim": "#ffb3af",
        "on-primary-fixed": "#410006",
        "on-primary-fixed-variant": "#930018",
        accent: "rgb(var(--accent-rgb) / <alpha-value>)",
        "accent-hover": "rgb(var(--accent-hover-rgb) / <alpha-value>)",
        "accent-light": "rgb(var(--accent-light-rgb) / <alpha-value>)",
        secondary: "rgb(var(--on-surface-variant-rgb) / <alpha-value>)",
        "on-secondary": "rgb(var(--surface-container-rgb) / <alpha-value>)",
        "secondary-container": "rgb(var(--surface-container-highest-rgb) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--on-surface-variant-rgb) / <alpha-value>)",
        "secondary-fixed": "rgb(var(--surface-container-lowest-rgb) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--on-surface-variant-rgb) / <alpha-value>)",
        "on-secondary-fixed": "rgb(var(--on-surface-rgb) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--surface-container-highest-rgb) / <alpha-value>)",
        tertiary: "rgb(var(--on-surface-variant-rgb) / <alpha-value>)",
        "on-tertiary": "rgb(var(--surface-container-rgb) / <alpha-value>)",
        "tertiary-container": "rgb(var(--surface-variant-rgb) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--on-surface-rgb) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--surface-container-lowest-rgb) / <alpha-value>)",
        "tertiary-fixed-dim": "rgb(var(--on-surface-variant-rgb) / <alpha-value>)",
        "on-tertiary-fixed": "rgb(var(--on-surface-rgb) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--surface-container-highest-rgb) / <alpha-value>)",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "stack-xs": "4px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        gutter: "24px",
        "margin-page": "48px",
        unit: "8px",
      },
      maxWidth: {
        page: "1440px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        h1: ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        h2: ["32px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "700" }],
        h3: ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
