import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#1d1d1d",
        surface: "#1d1d1d",
        "surface-dim": "#1d1d1d",
        "surface-bright": "#38393a",
        "surface-container-lowest": "#0c0f0f",
        "surface-container-low": "#1a1c1c",
        "surface-container": "#1e2020",
        "surface-container-high": "#282a2b",
        "surface-container-highest": "#333535",
        "surface-variant": "#333535",
        "on-surface": "#e2e2e2",
        "on-surface-variant": "#e8bcb9",
        "inverse-surface": "#e2e2e2",
        "inverse-on-surface": "#2f3131",
        "on-background": "#e2e2e2",
        outline: "#af8785",
        "outline-variant": "#5e3f3d",
        "surface-tint": "#ffb3af",
        primary: "#ffb3af",
        "on-primary": "#68000e",
        "primary-container": "#e8002d",
        "on-primary-container": "#fffaf9",
        "inverse-primary": "#bf0023",
        "primary-fixed": "#ffdad7",
        "primary-fixed-dim": "#ffb3af",
        "on-primary-fixed": "#410006",
        "on-primary-fixed-variant": "#930018",
        secondary: "#c8c6c5",
        "on-secondary": "#313030",
        "secondary-container": "#474746",
        "on-secondary-container": "#b7b4b4",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#474746",
        tertiary: "#c8c6c5",
        "on-tertiary": "#303030",
        "tertiary-container": "#747373",
        "on-tertiary-container": "#fdfaf9",
        "tertiary-fixed": "#e4e2e1",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed": "#1b1c1c",
        "on-tertiary-fixed-variant": "#474746",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "stack-xs": "4px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        gutter: "24px",
        "margin-page": "48px",
        unit: "8px",
      },
      maxWidth: {
        page: "1440px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        h1: ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        h2: ["32px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "700" }],
        h3: ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
